baseURL = "https://Stefan-D-W.github.io/"
languageCode = "zh-cn"
title = "StefanÂ·DÂ·W çš„ç²¾ç¥ä¸–ç•Œ"
theme = "PaperMod"

[params]
    defaultTheme = "auto"
    displayFullContent = false
    ShowReadingTime = true
    ShowShareButtons = true
    ShowCodeCopyButtons = true

    [params.editPost]
    url = "https://github.com/Stefan-D-W/Stefan-D-W.github.io/edit/main/content"
    Text = "ğŸ“ ç¼–è¾‘æ­¤æ–‡" # ä½ å¯ä»¥æ”¹æˆä»»ä½•ä½ å–œæ¬¢çš„åå­—
    appendFilePath = true # è¿™ä¸€è¡Œæœ€é‡è¦ï¼Œå®ƒä¼šè‡ªåŠ¨å¸®ä½ å®šä½åˆ°å½“å‰æ–‡ç« çš„æ–‡ä»¶
    
    [params.homeInfoParams]
        Title = "ä½ å¥½ï¼Œæˆ‘æ˜¯ Stefan"
        Content = "åœ¨è¿™é‡Œï¼Œæˆ‘è®°å½•ç”Ÿæ´»ï¼Œå¯¹æŠ—å¹³åº¸ï¼Œå¯»æ‰¾è‡ªç”±ã€‚"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Stefan-D-W"

    [[menu.main]]
    identifier = "new_post"
    name = "â• æ–°å»ºåšå®¢"
    # è¿™ä¸ªé“¾æ¥æ˜¯ GitHub çš„é»‘ç§‘æŠ€ï¼Œç›´æ¥è¿›å…¥ posts æ–‡ä»¶å¤¹å¹¶å‡†å¤‡æ–°å»ºæ–‡ä»¶
    url = "https://github.com/Stefan-D-W/Stefan-D-W.github.io/new/main/content/posts"
    weight = 10
